-- ============================================
-- Cafe Bella OFFICIAL Seed Data
-- Based on actual menu photos - all real prices
-- Run AFTER schema.sql
-- ============================================

-- ─── CATEGORIES ───────────────────────────────────────────────────────────────
INSERT INTO categories (name, slug, icon, description, display_order) VALUES
  ('Omelettes',             'omelettes',         '🍳', 'Made with fresh eggs, served with hash browns or fruit, toast with butter & jelly', 1),
  ('Eggs & More',           'eggs-more',          '🥚', 'Farm fresh eggs any style, served with hash browns or fruit and buttered toast', 2),
  ('Skillets',              'skillets',           '🥘', 'All skillets include hash browns, toast, and two eggs any style — $11.99', 3),
  ('Pancakes & Waffles',    'pancakes-waffles',   '🧇', 'Fluffy buttermilk pancakes, Belgian waffles, and sweet specialties', 4),
  ('French Toast & Crepes', 'french-toast-crepes','🥞', 'Golden French toast and delicate crepes with your choice of toppings', 5),
  ('Breakfast Specials',    'breakfast-specials', '⭐', 'Eggs Benedict, biscuits & gravy, burritos, and daily specials', 6),
  ('Salads & Plates',       'salads-plates',      '🥗', 'All served with a complimentary cup of homemade soup', 7),
  ('Burgers',               'burgers',            '🍔', '1/3 lb. freshly ground beef on a toasted bun, served with fries and homemade soup', 8),
  ('Sandwiches & Wraps',    'sandwiches-wraps',   '🥪', 'Served with French fries or fruit and a complimentary cup of homemade soup', 9),
  ('Soups, Sides & Apps',   'sides-soups',        '🍲', 'Homemade soups, sides, and appetizers', 10),
  ('Desserts',              'desserts',           '🍰', 'Sweet endings to a perfect meal', 11),
  ('Beverages',             'beverages',          '☕', 'Freshly brewed coffee, juices, shakes, and more', 12),
  ('Kids Menu',             'kids',               '🧒', 'For children 12 and under — served with a kid''s drink', 13)
ON CONFLICT (slug) DO NOTHING;

-- ─── OMELETTES ────────────────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Feta Cheese Omelette',        'Made with fresh eggs, served with hash browns or fruit, toast with butter and jelly', 8.99, true, false, 1  FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'American Cheese Omelette',    'Made with fresh eggs, served with hash browns or fruit, toast with butter and jelly', 8.99, true, false, 2  FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Ham Omelette',                 'Made with fresh eggs, served with hash browns or fruit, toast with butter and jelly', 8.99, true, false, 3  FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Ham & Cheese Omelette',        'Made with fresh eggs, served with hash browns or fruit, toast with butter and jelly', 9.59, true, true,  4  FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Mushroom Omelette',            'Made with fresh eggs, served with hash browns or fruit, toast with butter and jelly', 8.99, true, false, 5  FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Bacon & Cheese Omelette',      'Made with fresh eggs, served with hash browns or fruit, toast with butter and jelly', 9.59, true, false, 6  FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Gyro Omelette with Feta Cheese','Made with fresh eggs and gyro meat, served with hash browns or fruit, toast with butter and jelly', 9.99, true, true, 7  FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Spinach & Feta Cheese Omelette','Made with fresh eggs, served with hash browns or fruit, toast with butter and jelly', 9.59, true, false, 8  FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Denver Omelette',              'Filled with green pepper, onion and ham. Served with hash browns or fruit and toast', 9.09, true, false, 9  FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Western Omelette',             'Filled with tomato, onion, ham, green pepper and American cheese', 9.59, true, false, 10 FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Veggie Omelette',              'Filled with green pepper, tomato, mushroom and onion', 8.99, true, false, 11 FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Broccoli & Cheese Omelette',   'With broccoli and American cheese', 9.59, true, false, 12 FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Taco Omelette',                'With taco meat, onions, green peppers, black olives, cheddar cheese, topped with lettuce and tomatoes', 9.59, true, false, 13 FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Farmer Omelette',              'With ground beef, onions, green peppers and cheddar cheese', 9.59, true, false, 14 FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Meat Omelette',                'With bacon, ham and sausage', 9.99, true, false, 15 FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Combo Omelette',              'With bacon, ham, sausage, onions, green peppers, mushrooms, tomatoes and cheddar cheese', 9.99, true, true, 16 FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'California Omelette',          'With spinach, tomatoes and cheddar cheese', 9.99, true, false, 17 FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chorizo Omelette',             'With chorizo, tomatoes, onions, jalapeño and cheddar cheese', 9.99, true, false, 18 FROM categories c WHERE c.slug = 'omelettes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Corned Beef Hash Omelette',    'With corned beef hash, onions, tomatoes, green peppers and cheddar cheese', 9.99, true, false, 19 FROM categories c WHERE c.slug = 'omelettes';

-- ─── EGGS & MORE ──────────────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Two Country Fresh Eggs',       'Farm fresh eggs any style, served with hash browns or fruit, buttered toast and jelly', 7.99, true, true,  1  FROM categories c WHERE c.slug = 'eggs-more';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Two Eggs with Meat',           'Two country fresh eggs with your choice of bacon, sausage or ham. Served with hash browns or fruit and toast', 8.99, true, true, 2  FROM categories c WHERE c.slug = 'eggs-more';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Corned Beef Hash & Two Eggs',  'Corned beef hash with two farm fresh eggs any style, hash browns, and toast', 10.79, true, false, 3 FROM categories c WHERE c.slug = 'eggs-more';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Country Fried Steak',          'Smothered with sausage gravy. Served with hash browns or fruit and toast', 13.99, true, true,  4  FROM categories c WHERE c.slug = 'eggs-more';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chicken Fried Steak',          'Choice of sausage gravy or hollandaise sauce. Served with hash browns or fruit and toast', 13.99, true, false, 5  FROM categories c WHERE c.slug = 'eggs-more';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Sausage Patties',              'Served with hash browns or fruit, buttered toast and jelly', 9.29, true, false, 6  FROM categories c WHERE c.slug = 'eggs-more';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Rib Eye Steak & Eggs',         'Charcoal rib eye steak with two country fresh eggs any style, hash browns or fruit, and toast', 15.99, true, true, 7  FROM categories c WHERE c.slug = 'eggs-more';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Sirloin Steak & Eggs',         'Charcoal sirloin steak with two country fresh eggs any style, hash browns or fruit, and toast', 13.99, true, true, 8  FROM categories c WHERE c.slug = 'eggs-more';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chopped Sirloin Steak & Eggs', 'Charcoal chopped sirloin with two country fresh eggs any style, hash browns or fruit, and toast', 12.99, true, false, 9  FROM categories c WHERE c.slug = 'eggs-more';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Gyros & Eggs',                 'Tender slices of gyro meat served with two eggs any style, hash browns or fruit, and toast', 11.99, true, true, 10 FROM categories c WHERE c.slug = 'eggs-more';

-- ─── SKILLETS ($11.99 each) ───────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Steak Fajita Skillet',        'Seasoned steak strips, onions, green peppers, tomatoes, and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, true,  1  FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Spanish Skillet',             'Seasoned ground beef, onions, green peppers, tomatoes, and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, false, 2  FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'House Skillet',               'Chopped sausage, onions, green peppers, tomatoes, and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, false, 3  FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Corned Beef Hash Skillet',    'Corned beef hash, onions, green peppers, tomatoes, and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, false, 4  FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chicken Skillet',             'Seasoned chicken breast, onions, green peppers, tomatoes, and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, true,  5  FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Veggie Skillet',              'Green peppers, onions, mushrooms, tomatoes, and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, false, 6  FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Meat Skillet',                'Bacon, sausage, ham and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, true,  7  FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Combo Skillet',               'Bacon, sausage, ham, green peppers, onions, mushrooms, tomatoes, and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, true,  8  FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Mediterranean Skillet',       'Gyro meat, green peppers, tomatoes, onions, and feta cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, false, 9  FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Benedict Skillet',            'Ham, green peppers, tomatoes, red onions, and hollandaise sauce. Includes hash browns, toast, and two eggs any style', 11.99, true, false, 10 FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chorizo Skillet',             'Chorizo, green peppers, onions, tomatoes, jalapeños, and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, false, 11 FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Sirloin Tips Skillet',        'Sautéed sirloin tips, marinated onions and mushrooms, and cheddar cheese. Includes hash browns, toast, and two eggs any style', 11.99, true, false, 12 FROM categories c WHERE c.slug = 'skillets';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chicken Chipotle Skillet',    'Seasoned chicken breast, green peppers, onions, tomatoes, cheddar cheese, topped with chipotle sauce. Includes hash browns, toast, and two eggs any style', 11.99, true, false, 13 FROM categories c WHERE c.slug = 'skillets';

-- ─── PANCAKES & WAFFLES ───────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Fluffy Buttermilk Pancakes (3)',       '3 light and fluffy buttermilk pancakes', 8.79, true, true,  1  FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Fruit Pancakes (3)',                   'Your choice of apple, blueberry, cherry, or strawberry', 9.79, true, false, 2  FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Short Stack Buttermilk Pancakes (2)',  '2 fluffy buttermilk pancakes', 7.79, true, false, 3  FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Short Stack Fruit Pancakes (2)',       '2 fruit pancakes, your choice of apple, blueberry, cherry or strawberry', 8.79, true, false, 4  FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Tropical Pancakes',                   'Banana, kiwi, and strawberry with raspberry sauce', 9.99, true, true,  5  FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chocolate Chip Pancakes',             '3 fluffy pancakes loaded with chocolate chips', 9.29, true, false, 6  FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Pecan Pancakes',                      '3 fluffy pancakes topped with crunchy pecans', 9.29, true, false, 7  FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Pigs in a Blanket (3)',               'Sausage wrapped in fluffy pancakes', 7.79, true, false, 8  FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Golden Brown Belgium Waffle',         'Classic Belgian waffle. With blueberry, cherry, strawberry, or apple add $0.90', 8.39, true, true,  9  FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Alaskan Belgium Waffle',              'Belgian waffle with vanilla ice cream, strawberry, and whipped cream', 9.79, true, false, 10 FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Tropical Waffle',                     'Belgian waffle with banana, kiwi, and strawberry with raspberry sauce', 9.99, true, false, 11 FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Banana Split Pancakes',               '3 pancakes served with bananas, strawberries, vanilla ice cream, whipped cream, caramel and chocolate sauce', 8.25, true, false, 12 FROM categories c WHERE c.slug = 'pancakes-waffles';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Banana Split Waffle',                 'Belgian waffle served with bananas, strawberries, vanilla ice cream, whipped cream, caramel and chocolate sauce', 8.25, true, false, 13 FROM categories c WHERE c.slug = 'pancakes-waffles';

-- ─── FRENCH TOAST & CREPES ────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'French Toast (3)',                     '3 slices of golden French toast. With blueberry, cherry, strawberry, or apple add $1.00', 8.79, true, true,  1  FROM categories c WHERE c.slug = 'french-toast-crepes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Short French Toast (2)',               '2 slices of golden French toast. With blueberry, cherry, strawberry, or apple add $1.00', 7.79, true, false, 2  FROM categories c WHERE c.slug = 'french-toast-crepes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Bavarian French Toast',               'Strawberry-banana French toast', 9.29, true, false, 3  FROM categories c WHERE c.slug = 'french-toast-crepes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Strawberry Cheesecake French Toast',  'Our famous strawberry cheesecake French toast', 9.99, true, true,  4  FROM categories c WHERE c.slug = 'french-toast-crepes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Tropical French Toast',               'French toast with banana, kiwi, and strawberry with raspberry sauce', 9.99, true, false, 5  FROM categories c WHERE c.slug = 'french-toast-crepes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, '3 Crepes (Strawberry, Blueberry or Cherry)', '3 delicate crepes served with whipped cream', 8.99, true, true,  6  FROM categories c WHERE c.slug = 'french-toast-crepes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Strawberry-Banana-Nutella Crepe',     'Topped with whipped cream and chocolate sauce', 9.29, true, false, 7  FROM categories c WHERE c.slug = 'french-toast-crepes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Bavarian Crepes',                     'Strawberry-banana crepes', 9.29, true, false, 8  FROM categories c WHERE c.slug = 'french-toast-crepes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, '3 Strawberry or Blueberry Blintz',    '3 delicate blintzes with cream cheese', 8.99, true, false, 9  FROM categories c WHERE c.slug = 'french-toast-crepes';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Banana Split Crepes',                  'Crepes served with bananas, strawberries, vanilla ice cream, whipped cream, caramel and chocolate sauce', 8.25, true, false, 10 FROM categories c WHERE c.slug = 'french-toast-crepes';

-- ─── BREAKFAST SPECIALS ───────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Eggs Benedict with Canadian Bacon',  'Two poached eggs smothered in hollandaise sauce on an English muffin. Choice of hash browns or fruit', 10.99, true, true,  1  FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Eggs Benedict with Crab Meat',       'Crab meat Benedict smothered in hollandaise sauce on an English muffin', 11.29, true, false, 2  FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'California Eggs Benedict',           'With cherry tomatoes, fresh spinach, and avocados, smothered in hollandaise sauce', 11.99, true, false, 3  FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Mediterranean Eggs Benedict',        'With chicken breast and fresh spinach, smothered in hollandaise sauce on an English muffin', 11.99, true, false, 4  FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Biscuits & Gravy',                   'Freshly made biscuits smothered with rich sausage gravy (add 2 eggs +$1.00)', 9.99, true, true,  5  FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, '2+2+2 Special',                      'Two eggs, two pancakes (French toast or crepes), two pieces of bacon, sausage, or ham', 10.99, true, true,  6  FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Two Fried Egg Croissant',            'Served with bacon or ham, garnished with fresh fruit', 9.99, true, false, 7  FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Denver Burrito',                     'Filled with 3 scrambled eggs, green pepper, onion, ham, and cheddar cheese. Served with sour cream, salsa, and choice of fruit or hash browns', 9.99, true, false, 8  FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Western Burrito',                    'Filled with 3 scrambled eggs, tomato, onion, ham, green pepper, and cheddar cheese. Served with sour cream, salsa, and choice of fruit or hash browns', 9.99, true, false, 9  FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Veggie Burrito',                     'Filled with 3 scrambled eggs, green pepper, tomato, mushroom, onion, and cheddar cheese. Served with sour cream and salsa', 9.99, true, false, 10 FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Bacon Burrito',                      'Served with bacon, 3 scrambled eggs, and cheddar cheese. With sour cream and salsa', 9.99, true, false, 11 FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Sausage Burrito',                    'Served with sausage, 3 scrambled eggs, and cheddar cheese. With sour cream and salsa', 9.99, true, false, 12 FROM categories c WHERE c.slug = 'breakfast-specials';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Ham Burrito',                        'Served with ham, 3 scrambled eggs, and cheddar cheese. With sour cream and salsa', 9.99, true, false, 13 FROM categories c WHERE c.slug = 'breakfast-specials';

-- ─── SALADS & PLATES ──────────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chicken Special Salad',     'Romaine & Spring Mix, dried cranberries, pecans, strawberries, cherry tomatoes, cucumbers, boiled egg, and Provolone cheese. Served with a cup of homemade soup', 11.99, true, true,  1  FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Cobb Salad',                 'Romaine & Spring Mix, bacon, red onions, boiled egg, cucumbers, cherry tomatoes, black olives, and cheddar cheese. Served with a cup of homemade soup', 10.99, true, false, 2  FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chef''s Salad',              'Beef, turkey, Romaine & Spring Mix, cherry tomatoes, cucumbers, boiled egg, and cheddar cheese. Served with a cup of homemade soup', 10.99, true, false, 3  FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Taco Salad',                 'Seasoned ground beef or chicken breast with lettuce, tomato, onion, black olives, cheddar cheese, sour cream and salsa in an edible tortilla bowl. Served with a cup of homemade soup', 10.99, true, false, 4  FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Steak Salad',                'Romaine & Spring Mix, red onions, cherry tomatoes, cucumbers, cheddar cheese and avocado ranch dressing. Served with a cup of homemade soup', 11.29, true, false, 5  FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Southwest Chicken Salad',    'Cajun chicken, Romaine & Spring Mix, onions, cherry tomatoes, avocado, cheddar cheese, crisp tortilla strips, and ranch salsa dressing', 10.99, true, false, 6  FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Buffalo Chicken Strip Salad','Chicken strips tossed in Buffalo sauce, Romaine & Spring Mix, onions, celery, cherry tomatoes, avocado, Monterey cheese, and ranch or bleu cheese dressing', 10.99, true, false, 7  FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Athenian Salad',             'Lettuce with feta cheese, tomato, black olives, green pepper, cucumber, boiled egg, served with vinegar and oil dressing', 10.99, true, false, 8  FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Wedge Salad',                'Romaine & Spring Mix, bacon, cherry tomatoes, boiled egg, feta cheese, and bleu cheese dressing', 10.49, true, false, 9  FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Julienne Salad',             'Lettuce topped with ham, turkey, American cheese, tomato, cucumber, and a boiled egg, with your choice of dressing', 10.99, true, false, 10 FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Santa Fe Salad',             'Blackened chicken, Romaine & Spring Mix, red onions, cherry tomatoes, jalapeños, cheddar cheese, crisp tortilla strips, with salsa ranch', 10.99, true, false, 11 FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Gyros Plate',                'Tender slices of gyros layered on nutritious pita bread with onion, tomato, and cucumber sauce. Served with a small Grecian salad and choice of potato', 14.49, true, true,  12 FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Fresh Fruit Plate',          'Assorted fruits served with cottage cheese or ice cream and raisin toast. Served with a cup of homemade soup', 11.99, true, false, 13 FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chicken Delight',            'Chicken breast served with cottage cheese, tomato, cucumber, boiled egg, and fresh fruit. Served with a cup of homemade soup', 12.99, true, false, 14 FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Weight Watchers',            'Broiled, lean center cut sirloin steak, served with cottage cheese, hard-boiled egg, sliced tomato, cucumber, and fresh fruit garnish', 13.99, true, false, 15 FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Crab Meat Salad',            'Romaine & Spring Mix, cherry tomatoes, cheese, cucumber, and boiled egg. Served with a cup of homemade soup', 10.99, true, false, 16 FROM categories c WHERE c.slug = 'salads-plates';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Blackened Shrimp Salad',     'Romaine & Spring Mix, cherry tomatoes, cheese, cucumber, and boiled egg. Served with a cup of homemade soup', 13.00, true, false, 17 FROM categories c WHERE c.slug = 'salads-plates';

-- ─── BURGERS ──────────────────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Beef Burger',            '1/3 lb. freshly ground beef on a toasted bun. Served with pickle, French fries or fruit, and a cup of homemade soup', 10.79, true, false, 1  FROM categories c WHERE c.slug = 'burgers';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'The Wisconsin Burger',   '1/3 lb. beef burger with American cheese. Served with pickle, French fries or fruit, and a cup of homemade soup', 11.29, true, false, 2  FROM categories c WHERE c.slug = 'burgers';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Bacon Cheeseburger',     '1/3 lb. beef burger with a thick slice of cheese and crispy bacon. Served with pickle, French fries or fruit, and a cup of homemade soup', 12.09, true, true,  3  FROM categories c WHERE c.slug = 'burgers';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Alpine Burger',          '1/3 lb. beef burger with sautéed mushrooms, bacon, and Swiss cheese. Served with pickle, French fries or fruit, and a cup of homemade soup', 12.09, true, false, 4  FROM categories c WHERE c.slug = 'burgers';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Mushroom & Swiss Burger','1/3 lb. beef burger with sautéed mushrooms and Swiss cheese. Served with pickle, French fries or fruit, and a cup of homemade soup', 11.79, true, false, 5  FROM categories c WHERE c.slug = 'burgers';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Double Cheese Burger',   'Double 1/3 lb. beef patties with American cheese. Served with pickle, French fries or fruit, and a cup of homemade soup', 12.99, true, false, 6  FROM categories c WHERE c.slug = 'burgers';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Super Burger',           '1/2 lb. beef burger with raw onion on rye bread with chef''s garnish. Served with pickle, French fries or fruit, and a cup of homemade soup', 12.19, true, false, 7  FROM categories c WHERE c.slug = 'burgers';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Patty Melt',             '1/3 lb. burger with grilled onion and American cheese on grilled rye bread. Served with pickle, French fries or fruit, and a cup of homemade soup', 11.99, true, false, 8  FROM categories c WHERE c.slug = 'burgers';

-- ─── SANDWICHES & WRAPS ───────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Gyros Sandwich',                    'Served on pita bread with onion, tomato, cucumber sauce and French fries. With a cup of homemade soup', 12.75, true, true,  1  FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Grilled Chicken Breast Sandwich',  'Grilled chicken breast served on a bun with French fries or fruit, and a cup of homemade soup', 11.09, true, false, 2  FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Southwestern Chicken Sandwich',    'Chicken breast seasoned with barbecue sauce and topped with mozzarella cheese. Served with fries or fruit, and a cup of homemade soup', 11.29, true, false, 3  FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Buffalo Bleu Chicken Sandwich',    'Grilled chicken breast with Buffalo sauce and bleu cheese dressing. Served with fries or fruit, and a cup of homemade soup', 11.49, true, false, 4  FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chicken Cordon Bleu Sandwich',     'Boneless chicken breast topped with ham, Canadian bacon, and Swiss cheese. Served with fries or fruit, and a cup of homemade soup', 11.49, true, false, 5  FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Cajun Chicken Sandwich',           'Blackened chicken breast with cheddar cheese. Served with fries or fruit, and a cup of homemade soup', 11.19, true, false, 6  FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Philly Sub',                        'With green peppers, onions, mushrooms, provolone cheese and mayo on a sub roll. Served with fries, and a cup of homemade soup', 12.99, true, false, 7  FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'French Dip',                        'Tender slices of roast beef on French bread with au jus for dipping. Served with fries, and a cup of homemade soup', 11.99, true, false, 8  FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Monte Cristo',                      'French toast topped with ham and Swiss cheese, grilled to perfection. Served with fries, and a cup of homemade soup', 11.49, true, false, 9  FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Reuben',                            'Classic Reuben with sauerkraut on rye bread with Swiss cheese. Served with fries, and a cup of homemade soup', 11.89, true, false, 10 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Fish Sandwich',                     'Served on a toasted bun with fries or fruit, and a cup of homemade soup', 11.29, true, false, 11 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Club Sandwich',                     'BLT Club, Turkey Club, Ace of Clubs, or Ham & American Cheese — on toast with French fries or fruit, and a cup of homemade soup', 11.99, true, false, 12 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Open Face Hot Sandwich',           'Hot Ham, Hot Pork, Hot Beef, Hot Turkey or Hot Hamburger with mashed potatoes, gravy, and a cup of homemade soup', 11.79, true, false, 13 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'BLT on Toast',                      'Classic BLT with crispy bacon, lettuce, and fresh tomato on toast', 10.69, true, false, 14 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chicken Strips',                    'Served with French fries and your choice of sauce. With a cup of homemade soup', 12.75, true, false, 15 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Turkey Bacon Wrap',                 'Turkey breast, crispy bacon, lettuce, cheddar, and creamy ranch. Served with pickle, fries or fruit, and a cup of homemade soup', 11.29, true, true,  16 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Fajita Wrap',                       'Steak or chicken, green peppers, onion, cheddar, tomato, served with mild salsa. Served with pickle, fries or fruit, and a cup of homemade soup', 11.59, true, false, 17 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chicken Caesar Wrap',               'Grilled chicken breast, Romaine lettuce, tomatoes, and parmesan creamy Caesar dressing. Served with pickle, fries or fruit, and a cup of homemade soup', 11.49, true, false, 18 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chipotle Chicken Wrap',             'Grilled chicken breast, tomato, lettuce, onion, and chipotle dressing. Served with pickle, fries or fruit, and a cup of homemade soup', 11.49, true, false, 19 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Chicken-Bacon Wrap',                'Grilled chicken breast with bacon, tomato, onion, cheddar cheese, and creamy ranch dressing. Served with pickle, fries or fruit, and a cup of homemade soup', 11.49, true, false, 20 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Gigantic Roll Up Special',         'Chicken or roasted beef in a gigantic flour tortilla with green pepper, mushrooms, onion, mozzarella cheese. Served with sour cream and salsa', 12.55, true, false, 21 FROM categories c WHERE c.slug = 'sandwiches-wraps';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Turkey Melt',                       'All-white tender turkey meat topped with Swiss cheese on grilled rye bread. Served with pickle, fries or fruit, and a cup of homemade soup', 11.99, true, false, 22 FROM categories c WHERE c.slug = 'sandwiches-wraps';

-- ─── SOUPS, SIDES & APPETIZERS ────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Homemade Soup - Bowl',     'All made fresh daily. Ask your server for today''s selections', 3.79, true, true,  1  FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Homemade Soup - Cup',      'All made fresh daily. Ask your server for today''s selections', 3.09, true, false, 2  FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Side Salad',               'Fresh house salad', 3.59, true, false, 3  FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Breaded Mushrooms',         'Deep fried to a golden brown', 6.99, true, true,  4  FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Cheese Curds',              'Wisconsin cheese curds, golden fried', 7.75, true, true,  5  FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Battered Onions',           'Golden battered onion rings', 6.89, true, false, 6  FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Hash Browns',               'Golden shredded hash browns, just tell us how you like ''em', 3.00, true, true,  7  FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Any Choice of Potato',      'Hash browns, fries, or mashed — just tell us how you like ''em', 3.00, true, false, 8  FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Ham, Bacon, or Sausage',    'Your choice of breakfast meat', 3.99, true, false, 9  FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Corned Beef Hash',          'Classic corned beef hash side', 5.00, true, false, 10 FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Toast & Jelly',             'White, wheat, or sourdough with butter and jelly', 2.75, true, false, 11 FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Pecan Roll',                'Freshly baked pecan roll', 4.99, true, false, 12 FROM categories c WHERE c.slug = 'sides-soups';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Dinner Roll',               'Freshly baked dinner roll', 0.69, true, false, 13 FROM categories c WHERE c.slug = 'sides-soups';

-- ─── DESSERTS ─────────────────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Assorted Cakes',       'Ask your server for today''s cake selections', 4.49, true, false, 1  FROM categories c WHERE c.slug = 'desserts';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Assorted Fruit Pies',  'Ask your server for today''s pie selections', 4.49, true, false, 2  FROM categories c WHERE c.slug = 'desserts';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Pie A-La-Mode',        'Your choice of pie served with vanilla ice cream', 4.49, true, false, 3  FROM categories c WHERE c.slug = 'desserts';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Plain Cheesecake',     'Classic New York style cheesecake', 4.49, true, true,  4  FROM categories c WHERE c.slug = 'desserts';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Cherry Cheesecake',    'Creamy cheesecake topped with cherry sauce', 4.49, true, false, 5  FROM categories c WHERE c.slug = 'desserts';

-- ─── BEVERAGES ────────────────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Coffee',                        'Freshly brewed Superior special blend. Regular or decaffeinated — free refills', 2.69, true, true,  1  FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Freshly Squeezed Orange Juice', 'Fresh squeezed every morning', 5.99, true, true,  2  FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Iced Coffee',                   'Chilled brewed coffee over ice', 5.29, true, false, 3  FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Cappuccino',                    'French vanilla or salted caramel', 5.29, true, false, 4  FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Pepsi Products',                'Pepsi, Diet Pepsi, Sierra Mist, and more', 2.69, true, false, 5  FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Iced Tea or Hot Tea',           'Your choice of iced or hot tea', 2.89, true, false, 6  FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Lemonade',                      'Freshly made lemonade', 4.29, true, false, 7  FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Raspberry Lemonade',            'Freshly made raspberry lemonade', 4.79, true, false, 8  FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Hot Chocolate',                 'Rich and creamy hot chocolate', 3.99, true, false, 9  FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Milk',                          'White or chocolate — Small $2.49 / Large $3.29', 2.49, true, false, 10 FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Milk Shake',                    'Chocolate, strawberry, or vanilla', 5.99, true, true,  11 FROM categories c WHERE c.slug = 'beverages';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Juice',                         'Orange, cranberry, apple, grape, grapefruit, or tomato (Large)', 4.99, true, false, 12 FROM categories c WHERE c.slug = 'beverages';

-- ─── KIDS MENU ────────────────────────────────────────────────────────────────
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Big Birds Breakfast',        '1 egg, 1 pancake, 2 bacon strips or sausage. Served with a kid''s drink', 6.99, true, false, 1  FROM categories c WHERE c.slug = 'kids';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Egg Breakfast',               '1 egg any style, choice of 2 bacon or sausages, hash browns and 1 slice of toast. Served with a kid''s drink', 6.99, true, false, 2  FROM categories c WHERE c.slug = 'kids';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Pancake Breakfast',           '1 fluffy buttermilk pancake with 2 bacon or sausages. Served with a kid''s drink', 5.99, true, false, 3  FROM categories c WHERE c.slug = 'kids';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'French Toast Breakfast',      '1 slice of French toast with 2 bacon strips or sausages. Served with a kid''s drink', 5.99, true, false, 4  FROM categories c WHERE c.slug = 'kids';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Kids Hamburger with Fries',   'Kid-sized hamburger with French fries. Served with a kid''s drink', 7.99, true, false, 5  FROM categories c WHERE c.slug = 'kids';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Kids Cheeseburger with Fries','Kid-sized cheeseburger with French fries. Served with a kid''s drink', 7.99, true, false, 6  FROM categories c WHERE c.slug = 'kids';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Kids Grilled Cheese & Fries', 'Grilled cheese sandwich with French fries. Served with a kid''s drink', 7.99, true, false, 7  FROM categories c WHERE c.slug = 'kids';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Kids Fish Sandwich & Fries',  'Fish sandwich with French fries. Served with a kid''s drink', 7.99, true, false, 8  FROM categories c WHERE c.slug = 'kids';
INSERT INTO products (category_id, name, description, price, is_available, is_popular, display_order) SELECT c.id, 'Kids Chicken Strips & Fries', 'Chicken strips with French fries. Served with a kid''s drink', 7.99, true, false, 9  FROM categories c WHERE c.slug = 'kids';

-- ─── APPROVED REVIEWS ─────────────────────────────────────────────────────────
INSERT INTO reviews (customer_name, rating, comment, is_approved) VALUES
  ('Sarah M.',    5, 'Best breakfast spot in Sheboygan! The Combo Skillet is absolutely incredible. The staff is always so friendly and welcoming.',          true),
  ('James K.',    5, 'I''ve been coming here every Sunday for 3 years. The Eggs Benedict is perfect every single time. Real comfort food done right.',        true),
  ('Emily R.',    4, 'Wonderful little cafe with a cozy atmosphere. The Strawberry Cheesecake French Toast melts in your mouth. Definitely a regular now!',   true),
  ('Michael T.',  5, 'The coffee is fantastic and always hot, with free refills! Great place to start the morning. Service is quick even when they''re busy.', true),
  ('Lisa D.',     5, 'Brought my family here for brunch — everyone loved it! Kids especially loved the pancakes. The Gyros Plate was amazing too!',           true),
  ('Robert J.',   4, 'Great food at fair prices. The Bacon Cheeseburger at lunch is a hidden gem. Highly recommend the cheese curds as a starter!',           true),
  ('Karen W.',    5, 'The Strawberry Cheesecake French Toast is worth every penny. The Western Omelette is huge and delicious. Will be back!',                true),
  ('Tom H.',      5, 'Beef noodle soup, gyro plate — yummy! Don''t forget the fresh squeezed orange juice and coffee. Tastiest savory lunch of our trip!',   true)
ON CONFLICT DO NOTHING;
